// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAvailableSandbox(arg1) {
  return window['go']['main']['App']['AddAvailableSandbox'](arg1);
}

export function GetAppState() {
  return window['go']['main']['App']['GetAppState']();
}

export function GetAvailableSandboxes() {
  return window['go']['main']['App']['GetAvailableSandboxes']();
}

export function GetFileIcon(arg1) {
  return window['go']['main']['App']['GetFileIcon'](arg1);
}

export function IsSandboxieAvailable() {
  return window['go']['main']['App']['IsSandboxieAvailable']();
}

export function LaunchProgram(arg1) {
  return window['go']['main']['App']['LaunchProgram'](arg1);
}

export function OpenConfigFile() {
  return window['go']['main']['App']['OpenConfigFile']();
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function RemoveAvailableSandbox(arg1) {
  return window['go']['main']['App']['RemoveAvailableSandbox'](arg1);
}

export function RemoveFolder(arg1) {
  return window['go']['main']['App']['RemoveFolder'](arg1);
}

export function SelectFolder(arg1) {
  return window['go']['main']['App']['SelectFolder'](arg1);
}

export function SetCurrentFolder(arg1) {
  return window['go']['main']['App']['SetCurrentFolder'](arg1);
}

export function SetSelectedSandbox(arg1) {
  return window['go']['main']['App']['SetSelectedSandbox'](arg1);
}
